# Client with global options in TOML format
mode = "client"
log_lvl = "DEBUG"
no_color = false

[client]
local_to_remote = ["tcp://8080:localhost:80"]
remote_addr = "ws://localhost:9090"
connection_min_idle = 5
